POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "teste2",
    "email": "usuario@email.com",
    "password": "23432535"
}

###

GET http://localhost:3003/user/get


###

POST http://localhost:3003/movie/create
Content-Type: application/json

{
    "title": "The Lord of the Rings: the Fellowship of the Ring",
    "description": "In a fantastic and unique land, a hobbit receives as a gift from his uncle a magical and evil ring that must be destroyed before it falls into the hands of evil. For this, the hobbit Frodo has an arduous path ahead, where he encounters danger, fear and bizarre beings. By his side for the accomplishment of this journey, he can gradually count on other hobbits, an elf, a dwarf, two humans and a wizard, totaling nine beings that form the Fellowship of the Ring.",
    "duration_in_minutes": 178,
    "year_of_release": 2001
}