POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "nome": "Érick Jacquin",
    "email": "Jacquin@masterchef.com",
    "senha": "pombaeratoquevoa"
}

###

POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "Jacquin@masterchef.com",
    "senha": "pombaeratoquevoa"
}

###

PUT http://localhost:3003/user/edit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiYmU1MTQ0LThlMzQtNDgyNi1iMGE3LTNiMmM4ZDk5MDlkOSIsImlhdCI6MTY2ODEyNDA0MiwiZXhwIjoxNjY4MTI3NjQyfQ.AifhbicaquK3oZmxV1TDSr3vRT2zJQjGg2prrfbFkEc
Content-Type: application/json

{
    "name": "Harry Osbourne",
    "nickname": "Duende"
}

###

GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiYmU1MTQ0LThlMzQtNDgyNi1iMGE3LTNiMmM4ZDk5MDlkOSIsImlhdCI6MTY2ODEyODgzMSwiZXhwIjoxNjY4MTMyNDMxfQ.kZlCcLXhDagDYdrXEamSNl2cwqxPsPJSt5lSFCFwXq0