POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "nome": "Érick Jacquin",
    "email": "Jacquin@masterchef.com",
    "senha": "pombaeratoquevoa"
}

###

POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "Jacquin@masterchef.com",
    "senha": "pombaeratoquevoa"
}

###

GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5NzI0OGFlLTdiZmItNDEwMC1hZjQ4LWE5ZmZhNzY2MDdhZSIsImlhdCI6MTY2ODIxODEwNywiZXhwIjoxNjY4MjIxNzA3fQ.MJXdhTnoWI0vo_99mO43kHYMbLXnDJtdOELyVbOhyHY

###

GET http://localhost:3003/user/:297248ae-7bfb-4100-af48-a9ffa76607ae
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5NzI0OGFlLTdiZmItNDEwMC1hZjQ4LWE5ZmZhNzY2MDdhZSIsImlhdCI6MTY2ODIxODEwNywiZXhwIjoxNjY4MjIxNzA3fQ.MJXdhTnoWI0vo_99mO43kHYMbLXnDJtdOELyVbOhyHY